version: "3"
services:
  web-app:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /usr/apps/react_app/node_modules
      - .:/usr/apps/react_app
